AllCops:
  Excludes:
    - db/**/*.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'spec/*/*.rb'
