AllCops:
  Exclude:
    - db/**/*.rb
    - lib/templates/**/*.rb
    - log/**/*
    - node_modules/**/*
    - notes/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'spec/*/*.rb'
Metrics/LineLength:
  Max: 100


Style/ClassAndModuleChildren:
  Exclude:
    - 'app/api/v1/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
