AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*.rb
    - lib/templates/**/*.rb
    - log/**/*
    - node_modules/**/*
    - notes/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/api/v1/*.rb'
    - 'app/workers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'app/policies/**/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
