AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - pgdata/**/*
    - db/**/*.rb
    - lib/templates/**/*.rb
    - log/**/*
    - node_modules/**/*
    - notes/**/*
    - config/environments/production.rb

Documentation:
  Enabled: false
EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15 # default = 10
Metrics/AbcSize:
  Max: 18 # default = 15

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/api/v1/*.rb'
    - 'app/workers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'app/policies/**/*.rb'
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Naming/VariableNumber:
  Enabled: false
