version: '3.5'
networks:
  stamp:
    driver: overlay
    attachable: true
services:
  web:
    # dev image:        registry.safing.network/dev/stamp:latest
    # production image: registry.safing.network/server/stamp:latest
    # image: local/dev/stamp:latest
    image: registry.safing.network/dev/stamp:latest
    entrypoint: /stamp/docker-rm-server-pid.sh
    # to sleep:
    # command: ["sh", "-c", "tail -f /dev/null"]
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/stamp
    ports:
      - '3000:3000'
    env_file: .docker_rails_env
  postgres:
    image: postgres:9.6.3
    volumes:
      - ${STAMP}/data/pg:/pgdata
    environment:
      POSTGRES_DB: stamp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      PGDATA: /pgdata
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ${STAMP}/data/redis:/data
  sidekiq:
    # image: local/dev/stamp:latest
    image: registry.safing.network/dev/stamp:latest
    entrypoint: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/stamp
    env_file: .docker_rails_env
  guard:
    # image: local/dev/stamp:latest
    image: registry.safing.network/dev/stamp:latest
    command: guard --no-bundler-warning --no-interactions
    volumes:
      - .:/stamp
    tty: true # color the logs
    stdin_open: true
    environment:
      RAILS_ENV: test
      RACK_ENV: test
