version: '3.5'
networks:
  stamp:
    driver: overlay
    attachable: true
services:
  web:
    image: toolset.safing.network/rails:latest
    entrypoint: /bin/bash -c "cd /rails_app && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails_app
    ports:
      - '3000:3000'
    env_file: .docker_rails_env
  postgres:
    image: postgres:9.6.3
    volumes:
      - ${STAMP}/data/pg:/pgdata
    environment:
      POSTGRES_DB: stamp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      PGDATA: /pgdata
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ${STAMP}/data/redis:/data
  sidekiq:
    image: toolset.safing.network/rails:latest
    entrypoint: /bin/bash -c "cd /rails_app && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/rails_app'
    env_file: .docker_rails_env
