USER:
  INITIAL_REPUTATION: 0
  DAILY:
    VOTING_LIMIT: 1_000
    STAMP_CREATION_LIMIT: 100

BOT:
  DAILY:
    VOTING_LIMIT: 100_000
    STAMP_CREATION_LIMIT: 10_000

STAMP:
  ACCEPTED:
    CREATOR_BOUNTY: 10
    ACCEPT_BOUNTY: 1
    DENY_PENALTY: -5
  DENIED:
    CREATOR_PENALTY: -100
    ACCEPT_PENALTY: -10
    DENY_BOUNTY: 5
