USER:
  INITIAL_REPUTATION: 0
  DAILY:
    VOTING_LIMIT: 1_000
    STAMP_CREATION_LIMIT: 100

BOT:
  DAILY:
    VOTING_LIMIT: 100_000
    STAMP_CREATION_LIMIT: 10_000

STAMP::LABEL:
  CREATOR:
    PRIZE: 10 # created good stuff
    PENALTY: -100 # created trash
  UPVOTER:
    PRIZE: 1 # upvoted good stuff
    PENALTY: -10 # upvoted trash
  DOWNVOTER:
    PRIZE: 5 # downvoted trash
    PENALTY: -5 # downvoted good stuff
VOTABLE:
  POWER:
    THRESHOLD: 10 # min power a stamp needs to continue conclusion
    # if a votable falls below this, it will simply get rejected
  MAJORITY:
    THRESHOLD: 75 # in percent

FLAGS:
  # # write access
  # - any
  # - user
  # - admin
  # - system
  # internet access
  - name: internet
    group: 1
  - name: lan
    group: 1
  - name: localhost
    group: 1
  - name: none
    group: 1
  # domain decision logic
  - name: prompt
    group: 2
  - name: blacklist
    group: 2
  - name: whitelist
    group: 2
  # independent flags
  - name: service # accept incoming  connections
  - name: p2p # allow connections to IP adresses
