USER:
  INITIAL_REPUTATION: 0
  DAILY:
    VOTING_LIMIT: 1_000
    STAMP_CREATION_LIMIT: 100

BOT:
  DAILY:
    VOTING_LIMIT: 100_000
    STAMP_CREATION_LIMIT: 10_000

STAMP:
  CREATOR:
    PRIZE: 10 # created good stuff
    PENALTY: -100 # created trash
  UPVOTER:
    PRIZE: 1 # upvoted good stuff
    PENALTY: -10 # upvoted trash
  DOWNVOTER:
    PRIZE: 5 # downvoted trash
    PENALTY: -5 # downvoted good stuff
