---
:concurrency: 5
:logfile: /dev/stdout
staging:
  :concurrency: 10
production:
  :concurrency: 20
  :logfile: /dev/stdout
:queues:
  - critical
  - default
  - low

:schedule:
  recalc_counter_caches_worker:
    cron: '0 30 3 * * *' # once a day at 3:30 AM
    class: RecalcCounterCachesWorker
